export const ACCESSIBILITY_ON = 'ACCESSIBILITY_ON';
export const ACCESSIBILITY_OFF = 'ACCESSIBILITY_OFF';
export const SET_END_BUILDING_NODE = 'SET_END_BUILDING_NODE';
export const SET_START_BUILDING_NODE = 'SET_START_BUILDING_NODE';
export const RESET_NAVIGATION = 'RESET_NAVIGATION';
export const SEND_DIRECTIONS_TO_OUTDOOR = 'SEND_DIRECTIONS_TO_OUTDOOR';
