export const SET_END_BUILDING_NODE = 'SET_END_BUILDING_NODE';
export const SET_START_BUILDING_NODE = 'SET_START_BUILDING_NODE';
export const SET_FROM_WITHIN_BUILDING_NODE = 'SET_FROM_WITHIN_BUILDING_NODE';
export const RESET_NAVIGATION = 'RESET_NAVIGATION';
