export const SET_END_BUILDING_NODE = 'SET_END_BUILDING_NODE';
export const SET_START_BUILDING_NODE = 'SET_START_BUILDING_NODE';
export const SET_FROM_WITHIN_BUILDING_NODE = 'SET_FROM_WITHIN_BUILDING_NODE';
export const SET_FROM_WITHIN_END_NODE = 'SET_FROM_WITHIN_END_NODE';
export const END_FROM_WITHIN_INDOOR_READY = 'END_FROM_WITHIN_INDOOR_READY';
export const RESET_NAVIGATION = 'RESET_NAVIGATION';
export const SEND_DIRECTIONS_TO_OUTDOOR = 'SEND_DIRECTIONS_TO_OUTDOOR';
